# Generated by Django 5.1.5 on 2025-01-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('chatid', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Кто власть имеет', 'verbose_name_plural': 'Кто власть имеет'},
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tgid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('chats', models.ManyToManyField(to='validation.chat')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
