# Generated by Django 5.1.5 on 2025-01-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgid', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Кто власть имеет', 'verbose_name_plural': 'Кто власть имеет'},
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tgid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
