# Generated by Django 5.1.5 on 2025-01-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0002_chat_alter_tguser_options_alter_tguser_tgid_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='topic_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
