# Generated by Django 5.1.5 on 2025-01-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation', '0003_chat_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatid',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
